version: '3.7'
services:
  opensearch:
    image: opensearchproject/opensearch:1.2.0
    container_name: opensearch
    environment:
      discovery.type: single-node
      plugins.security.disabled: true
      compatibility.override_main_response_version: true
    ports:
      - 9200:9200
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:1.2.0
    container_name: opensearch-dashboards
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
      DISABLE_SECUIRITY_DAHSBOARDS_PLUGIN: "true"
    ports:
      - 5601:5601